#!/usr/bin/env python3
"""
Move the DVM-side parts so the routing to the DD-50 gets simpler, with the
pin swap re-done for every candidate placement.

What may move (everything else stays where place_components.py puts it):
  * the IC row: which register type sits in each of the seven slots
    (21 patterns), and the rotation of the 165s and of the 595s (90/270)
  * the DRDY buffer (U1) and its capacitor, and the SAMPLE MOSFET (Q1) with
    its pull-down: a few checked spots at the board ends
  * the order of the six optocouplers along the isolation barrier

Each candidate is scored with scripts/pin_swap.py's cost (ratsnest length +
CROSSING_MM per crossing) after a short pin-swap search. Fixed nets are
scored too: the DVM-side control nets (SCK/LATCH/OE_N/DRDY), the MOSFET
drain to SKB 39 and the six MCU <-> opto nets on the USB side. So the opto
order, the IC rotation and the part spots are judged on them as well.

    python3 scripts/optimise_placement.py           # report
    python3 scripts/optimise_placement.py --write   # update place_components.py

After --write:
    ~/.local/share/uv/tools/atopile/bin/python scripts/place_components.py
    ~/.local/share/uv/tools/atopile/bin/python scripts/check_layout.py
    python3 scripts/pin_swap.py --write && ato build

Needs KiCad's pcbnew Python module (KiCad 9/10).
"""

import argparse
import itertools
import math
import random
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import pin_swap as ps  # noqa: E402

PLACE = Path(__file__).resolve().parent / "place_components.py"
BEGIN, END = "# --- BEGIN DVM placement", "# --- END DVM placement"

SHORT_ITER = 6000  # pin-swap iterations per candidate
TOP = 6  # IC patterns carried into the spot search


# Candidate spots, all checked against check_layout.py (outline, overlaps,
# jackscrew keep-outs). "east" is the original placement.
U1_SPOTS = {
    "east": {"drdy_buffer.package": (33.5, 6.5, 0.0), "drdy_buffer.decoupling": (33.5, 9.0, 0.0)},
    "west": {"drdy_buffer.package": (-33.0, 15.3, 0.0), "drdy_buffer.decoupling": (-36.6, 15.3, 90.0)},
    "southwest": {"drdy_buffer.package": (-25.5, 27.6, 0.0), "drdy_buffer.decoupling": (-22.0, 27.6, 90.0)},
}
Q1_SPOTS = {
    "east": {"sample_fet": (34.0, 13.0, 0.0), "sample_fet_pulldown": (36.5, 13.0, 90.0)},
    "west": {"sample_fet": (-36.6, 20.5, 180.0), "sample_fet_pulldown": (-36.6, 23.5, 0.0)},
    "south": {"sample_fet": (-8.3, 27.6, 270.0), "sample_fet_pulldown": (-5.3, 27.6, 270.0)},
}


# ---------------------------------------------------------------- placement file
def read_block():
    text = PLACE.read_text(encoding="utf-8")
    i, j = text.index(BEGIN), text.index(END)
    env = {}
    exec(text[text.index("\n", i) + 1:j], {}, env)  # literal assignments only
    consts = {}
    for name in ("IC_SLOTS_X", "IC_ROW_Y", "OPTO_X", "OPTO_RX"):
        m = re.search(rf"^{name} = (.+)$", text, re.M)
        consts[name] = eval(m.group(1), {})  # literal
    return env, consts


def write_block(cfg):
    lines = [BEGIN + ": generated by scripts/optimise_placement.py ---",
             "IC_SLOT_ORDER = [  # register in each IC_SLOTS_X slot, east to west"]
    lines += [f'    "{a}",' for a in cfg["IC_SLOT_ORDER"]]
    lines += ["]", f"IC_ROTATION = {cfg['IC_ROTATION']!r}",
              "DVM_PARTS = {  # address -> (x, y, rotation), top face"]
    lines += [f'    "{a}": {tuple(v)!r},' for a, v in cfg["DVM_PARTS"].items()]
    lines += ["}", f"OPTO_ORDER = {cfg['OPTO_ORDER']!r}  # west to east", END + " ---"]
    text = PLACE.read_text(encoding="utf-8")
    i, j = text.index(BEGIN), text.index(END)
    j = text.index("\n", j)
    PLACE.write_text(text[:i] + "\n".join(lines) + text[j:], encoding="utf-8")


# ---------------------------------------------------------------- geometry
class Board:
    """Pad geometry of the current layout, with footprints re-placeable."""

    def __init__(self):
        import pcbnew

        self.local, self.pads, self.nets = {}, {}, {}
        board = pcbnew.LoadBoard(str(ps.LAYOUT))
        for fp in board.GetFootprints():
            addr = next((f.GetText() for f in fp.GetFields() if f.GetName() == "atopile_address"), "")
            X, Y = pcbnew.ToMM(fp.GetPosition().x), pcbnew.ToMM(fp.GetPosition().y)
            a = math.radians(fp.GetOrientationDegrees())
            for pad in fp.Pads():
                p = pad.GetPosition()
                dx, dy = pcbnew.ToMM(p.x) - X, pcbnew.ToMM(p.y) - Y
                key = (addr, pad.GetNumber())
                self.local[key] = (dx * math.cos(a) - dy * math.sin(a), dx * math.sin(a) + dy * math.cos(a))
                self.pads[key] = (X + dx, Y + dy)
                self.nets[key] = pad.GetNetname()

    def placed(self, moves):
        """pads dict with footprints in `moves` (addr -> (x, y, rot)) re-placed"""
        pads = dict(self.pads)
        for (addr, num), (lx, ly) in self.local.items():
            if addr in moves:
                X, Y, r = moves[addr]
                a = math.radians(r)
                pads[(addr, num)] = (X + lx * math.cos(a) + ly * math.sin(a), Y - lx * math.sin(a) + ly * math.cos(a))
        return pads


def moves_for(cfg, consts):
    m = {}
    for ic, x in zip(cfg["IC_SLOT_ORDER"], consts["IC_SLOTS_X"]):
        m[ic] = (x, consts["IC_ROW_Y"], cfg["IC_ROTATION"][ic.split("[")[0]])
        m[ic.replace(".package", ".decoupling")] = (x, consts["IC_ROW_Y"] - 6.4, 0.0)
    m.update(cfg["DVM_PARTS"])
    for name, x in zip(cfg["OPTO_ORDER"], consts["OPTO_X"]):
        rx = name in consts["OPTO_RX"]
        m[f"{name}.opto"] = (x, 0.0, 270.0 if rx else 90.0)
        m[f"{name}.led_resistor"] = (x - 3.4, 3.2 if rx else -3.2, 90.0)
        m[f"{name}.bypass"] = (x - 3.4, -3.2 if rx else 3.2, 90.0)
    return m


def evaluate(board, cfg, consts, start, iters, seed):
    pads = board.placed(moves_for(cfg, consts))
    geo = ps.Geometry(pads, board.nets)
    s = ps.State(geo, start.in_items, start.out_items, start.chain_in, start.chain_out,
                 fixed=ps.fixed_segs(pads, board.nets))
    if iters:
        ps.ITERATIONS = iters
        s = ps.anneal(s, random.Random(seed))
    return s.cost(), s


def describe(cfg):
    pattern = "".join("o" if a.startswith("shift_out") else "i" for a in cfg["IC_SLOT_ORDER"])
    return f"row {pattern} (E->W) rot165 {cfg['IC_ROTATION']['shift_in']:.0f} rot595 {cfg['IC_ROTATION']['shift_out']:.0f}"


def with_pattern(cfg, out_slots, rot_in, rot_out):
    order, i, o = [], 0, 0
    for slot in range(7):
        if slot in out_slots:
            order.append(f"shift_out[{o}].package")
            o += 1
        else:
            order.append(f"shift_in[{i}].package")
            i += 1
    return dict(cfg, IC_SLOT_ORDER=order, IC_ROTATION={"shift_in": rot_in, "shift_out": rot_out})


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--write", action="store_true", help="write the best placement into place_components.py")
    args = ap.parse_args()

    board = Board()
    block, consts = read_block()
    cur = {k: block[k] for k in ("IC_SLOT_ORDER", "IC_ROTATION", "DVM_PARTS", "OPTO_ORDER")}
    start = ps.current_state(ps.Geometry(board.pads, board.nets), board.nets)
    base_cost, base = evaluate(board, cur, consts, start, 0, 0)
    print(f"current placement + current pin map: cost {base_cost:7.1f} "
          f"({base.length():.0f} mm, {base.crossings()} crossings, incl. control nets)")

    # stage A: IC row pattern and rotations (DRDY buffer and MOSFET at the west end)
    west = dict(cur, DVM_PARTS={**U1_SPOTS["west"], **Q1_SPOTS["west"]})
    results = []
    for out_slots in itertools.combinations(range(7), 2):
        for rot_in, rot_out in itertools.product((90.0, 270.0), repeat=2):
            cfg = with_pattern(west, out_slots, rot_in, rot_out)
            cost, _ = evaluate(board, cfg, consts, start, SHORT_ITER, 1)
            results.append((cost, cfg))
    results.sort(key=lambda r: r[0])
    print("stage A, best IC rows:")
    for cost, cfg in results[:TOP]:
        print(f"  {cost:7.1f}  {describe(cfg)}")

    # stage B: spots for the DRDY buffer and the MOSFET
    spot_results = []
    for _, cfg in results[:TOP]:
        for (u, us), (q, qs) in itertools.product(U1_SPOTS.items(), Q1_SPOTS.items()):
            c = dict(cfg, DVM_PARTS={**us, **qs})
            cost, s = evaluate(board, c, consts, start, SHORT_ITER, 2)
            spot_results.append((cost, c, s, f"U1 {u}, Q1 {q}"))
    spot_results.sort(key=lambda r: r[0])
    print("stage B, best with part spots:")
    for cost, cfg, _, what in spot_results[:4]:
        print(f"  {cost:7.1f}  {describe(cfg)}, {what}")
    best_cost, best, best_state, _ = spot_results[0]

    # stage C: opto order, keeping the pin map found for this placement
    names = best["OPTO_ORDER"]
    for perm in itertools.permutations(names):
        c = dict(best, OPTO_ORDER=list(perm))
        cost, _ = evaluate(board, c, consts, best_state, 0, 0)
        if cost < best_cost - 1e-6:
            best_cost, best = cost, c
    cost, s = evaluate(board, best, consts, best_state, SHORT_ITER * 3, 3)
    print(f"best: cost {cost:7.1f} ({s.length():.0f} mm, {s.crossings()} crossings)  {describe(best)}")
    print(f"      parts {best['DVM_PARTS']}")
    print(f"      optos W->E {best['OPTO_ORDER']}")
    if args.write:
        write_block(best)
        print(f"wrote {PLACE.name}; now run place_components.py, check_layout.py, pin_swap.py --write, ato build")
    return 0


if __name__ == "__main__":
    sys.exit(main())
