"""
Initial component placement for the Solartron 7075 USB interface board.

Run with atopile's Python after `ato build` has created the layout:

    ~/.local/share/uv/tools/atopile/bin/python scripts/place_components.py

Board: 78 x 60 mm, centred on the PCB origin (x right, y down).
  - y > 0 (south): isolated DVM side. The DD-50 plug is on the BOTTOM
    face (it plugs into the 7075's SKB socket); all other parts are on top.
  - y < 0 (north): USB side. The vertical USB-B is on the TOP face.
  - y = 0: isolation barrier, crossed only by the six TLP2361s and the
    IB0505LS DC-DC. Nothing else may come within BARRIER_HALF_GAP of it.
  - 4 layers: F.Cu and B.Cu for signals, In1.Cu ground planes and In2.Cu
    supply planes (see add_zones), each split at the barrier.

Footprints are matched by their `atopile_address` property, so re-running
after a design change keeps working.
"""

import math
import sys
from pathlib import Path

from faebryk.exporters.pcb.kicad.transformer import PCB_Transformer
from faebryk.libs.kicad.fileformats import kicad

LAYOUT = Path(__file__).resolve().parent.parent / "layouts/default/default.kicad_pcb"

BOARD_W, BOARD_H = 78.0, 60.0
BARRIER_HALF_GAP = 2.0

# --- DVM side --------------------------------------------------------------
DSUB_Y = 21.8
IC_ROW_Y = 11.5
IC_SLOTS_X = [25.8, 17.2, 8.6, 0.0, -8.6, -17.2, -25.8]
OPTO_X = [-22.0, -14.0, -6.0, 2.0, 10.0, 18.0]
OPTO_RX = ("opto_miso", "opto_drdy")  # DVM -> MCU channels; the rest are MCU -> DVM

# --- BEGIN DVM placement: generated by scripts/optimise_placement.py ---
IC_SLOT_ORDER = [  # register in each IC_SLOTS_X slot, east to west
    "shift_in[0].package",
    "shift_out[0].package",
    "shift_in[1].package",
    "shift_out[1].package",
    "shift_in[2].package",
    "shift_in[3].package",
    "shift_in[4].package",
]
IC_ROTATION = {'shift_in': 270.0, 'shift_out': 90.0}
DVM_PARTS = {  # address -> (x, y, rotation), top face
    "drdy_buffer.package": (-33.0, 15.3, 0.0),
    "drdy_buffer.decoupling": (-36.6, 15.3, 90.0),
    "sample_fet": (-8.3, 27.6, 270.0),
    "sample_fet_pulldown": (-5.3, 27.6, 270.0),
}
OPTO_ORDER = ['opto_drdy', 'opto_miso', 'opto_latch', 'opto_mosi', 'opto_oe_n', 'opto_sck']  # west to east
# --- END DVM placement ---

# address -> (x, y, rotation, layer)
P: dict[str, tuple[float, float, float, str]] = {
    "dvm.connector": (0.0, DSUB_Y, 0.0, "B.Cu"),
    # misc isolated-side parts (the DRDY buffer and SAMPLE MOSFET are in DVM_PARTS)
    "oe_pullup": (-29.6, 3.8, 0.0, "F.Cu"),
    "iso_power_led.package": (36.0, 17.0, 90.0, "F.Cu"),
    "iso_power_led_resistor": (33.5, 17.0, 90.0, "F.Cu"),
    # isolated DC-DC on the west edge, straddling the barrier
    # (pins 1/2 at y = -5.08/-2.54, pins 4/6 at y = +2.54/+7.62)
    "iso_supply.converter": (-33.4, 1.27, 270.0, "F.Cu"),
    "iso_supply.input_capacitor": (-30.9, -6.0, 90.0, "F.Cu"),
    "iso_supply.output_capacitor": (-30.9, 7.5, 90.0, "F.Cu"),
    # --- USB side --------------------------------------------------------
    "usb_in.connector": (-26.0, -21.0, 0.0, "F.Cu"),
    "usb_in.esd": (-16.5, -17.5, 0.0, "F.Cu"),
    "usb_in.fuse": (-16.5, -13.0, 0.0, "F.Cu"),
    "usb_in.bulk": (-21.0, -12.0, 0.0, "F.Cu"),
    # MCU (QFN-60, pins 46-60 face north, 16-30 south, 1-15 west, 31-45 east)
    "mcu.package": (4.0, -17.0, 0.0, "F.Cu"),
    "mcu.vreg_inductor": (7.5, -23.0, 0.0, "F.Cu"),
    "mcu.vreg_cin": (5.0, -23.0, 90.0, "F.Cu"),
    "mcu.vreg_cout": (10.0, -23.0, 90.0, "F.Cu"),
    "mcu.vreg_avdd_r": (7.5, -25.0, 0.0, "F.Cu"),
    "mcu.vreg_avdd_c": (10.0, -25.0, 0.0, "F.Cu"),
    "mcu.usb_series_r[0]": (2.6, -23.0, 90.0, "F.Cu"),
    "mcu.usb_series_r[1]": (1.4, -23.0, 90.0, "F.Cu"),
    "mcu.bulk": (-4.2, -23.0, 90.0, "F.Cu"),
    # decoupling ~2 mm out from the pin tips: the planes feed them through
    # their own vias, and the gap leaves an escape channel for the pins
    "mcu.io_decoupling[0]": (-2.4, -19.5, 90.0, "F.Cu"),
    "mcu.io_decoupling[1]": (-2.4, -17.0, 90.0, "F.Cu"),
    "mcu.io_decoupling[2]": (-2.4, -14.5, 90.0, "F.Cu"),
    "mcu.io_decoupling[3]": (1.5, -10.6, 0.0, "F.Cu"),
    "mcu.io_decoupling[4]": (6.5, -10.6, 0.0, "F.Cu"),
    "mcu.io_decoupling[5]": (10.4, -14.5, 90.0, "F.Cu"),
    "mcu.io_decoupling[6]": (10.4, -19.5, 90.0, "F.Cu"),
    "mcu.io_decoupling[7]": (-0.2, -23.0, 90.0, "F.Cu"),
    "mcu.io_decoupling[8]": (-1.6, -23.0, 90.0, "F.Cu"),
    "mcu.core_decoupling[0]": (-3.9, -17.0, 90.0, "F.Cu"),
    "mcu.core_decoupling[1]": (4.0, -10.6, 0.0, "F.Cu"),
    "mcu.core_decoupling[2]": (11.9, -17.0, 90.0, "F.Cu"),
    "mcu.crystal": (-5.5, -11.0, 0.0, "F.Cu"),
    "mcu.crystal_load[0]": (-8.5, -11.0, 90.0, "F.Cu"),
    "mcu.crystal_load[1]": (-2.5, -11.0, 90.0, "F.Cu"),
    "mcu.crystal_series_r": (-5.5, -7.8, 0.0, "F.Cu"),
    "mcu.bootsel_button.package": (21.0, -26.0, 0.0, "F.Cu"),
    "mcu.reset_button.package": (28.0, -26.0, 0.0, "F.Cu"),
    "mcu.bootsel_r": (16.5, -21.0, 90.0, "F.Cu"),
    "mcu.run_pullup": (15.0, -17.0, 90.0, "F.Cu"),
    "swd_header.connector": (21.0, -19.0, 0.0, "F.Cu"),
    "power_led.package": (33.0, -21.0, 90.0, "F.Cu"),
    "power_led_resistor": (33.0, -18.0, 90.0, "F.Cu"),
    "status_led.package": (35.5, -21.0, 90.0, "F.Cu"),
    "status_led_resistor": (35.5, -18.0, 90.0, "F.Cu"),
}

# Library modules that arrive pre-routed (their sub-layout's tracks and vias
# are copied into this board as an atopile group). They are moved as one
# rigid block so the library's routing stays valid:
#   group name -> (library layout, anchor address, target x, y)
RIGID_GROUPS = {
    "ldo": (
        Path(__file__).resolve().parent.parent
        / ".ato/modules/atopile/ti-tlv75901/layouts/default/default.kicad_pcb",
        "package", -12.0, -25.0,
    ),
}

P.update({addr: (x, y, r, "F.Cu") for addr, (x, y, r) in DVM_PARTS.items()})

# Opto row on the barrier. TX: LED (pins 1/3) north; RX: LED south.
for name, x in zip(OPTO_ORDER, OPTO_X):
    north, south = (-3.2, 3.2)
    if name not in OPTO_RX:
        P[f"{name}.opto"] = (x, 0.0, 90.0, "F.Cu")
        P[f"{name}.led_resistor"] = (x - 3.4, north, 90.0, "F.Cu")
        P[f"{name}.bypass"] = (x - 3.4, south, 90.0, "F.Cu")
    else:
        P[f"{name}.opto"] = (x, 0.0, 270.0, "F.Cu")
        P[f"{name}.led_resistor"] = (x - 3.4, south, 90.0, "F.Cu")
        P[f"{name}.bypass"] = (x - 3.4, north, 90.0, "F.Cu")


def props(fp) -> dict[str, str]:
    return {p.name: p.value for p in fp.propertys}


def pad_abs(fp, pad) -> tuple[float, float]:
    """Absolute pad centre (KiCad rotates footprints counter-clockwise)."""
    a = math.radians(fp.at.r or 0)
    x, y = pad.at.x, pad.at.y
    return (
        fp.at.x + x * math.cos(a) + y * math.sin(a),
        fp.at.y - x * math.sin(a) + y * math.cos(a),
    )


# Zones this script owns. The first two are the old outer-layer pours, listed
# so that re-running removes them.
ZONE_NAMES = ("pour_GND", "pour_GND_ISO", "isolation_barrier",
              "plane_GND", "plane_GND_ISO", "plane_3V3", "plane_5V_ISO")
COPPER = ["F.Cu", "In1.Cu", "In2.Cu", "B.Cu"]

# 4-layer stack-up: JLCPCB's standard 1.6 mm 7628 build (nominal values from
# its help centre). In1 and In2 are plane layers (KiCad type "power"), so the
# Specctra export marks them as planes and Freerouting routes no tracks there.
#   name -> (type, thickness mm, material, epsilon_r)
STACKUP = [
    ("F.Cu", "copper", 0.035, None, None),
    ("dielectric 1", "prepreg", 0.2, "7628", 4.4),
    ("In1.Cu", "copper", 0.0175, None, None),
    ("dielectric 2", "core", 1.065, "FR4", 4.6),
    ("In2.Cu", "copper", 0.0175, None, None),
    ("dielectric 3", "prepreg", 0.2, "7628", 4.4),
    ("B.Cu", "copper", 0.035, None, None),
]
INNER_LAYERS = {"In1.Cu": 1, "In2.Cu": 2}  # KiCad 8/9 file layer numbers


def set_layer_stack(pcb) -> None:
    """Make the board 4 layers: add In1.Cu/In2.Cu as plane layers and write
    the copper/dielectric part of the stack-up (mask, paste and silk kept)."""
    # (copies: the list items are views into the file, so clear() frees them)
    layers = [(la.number, la.name, la.type, la.alias) for la in pcb.layers]
    layers = [la for la in layers if la[1] not in INNER_LAYERS]
    layers += [(n, name, kicad.pcb.E_layer_type.POWER, None) for name, n in INNER_LAYERS.items()]
    pcb.layers.clear()
    for number, name, typ, alias in sorted(layers):
        pcb.layers.append(kicad.pcb.Layer(number=number, name=name, type=typ, alias=alias))

    st = pcb.setup.stackup
    keep = [
        (sl.name, sl.type, sl.color, None if sl.thickness is None else sl.thickness.thickness,
         sl.material, sl.epsilon_r, sl.loss_tangent)
        for sl in st.layers
    ]
    top = [k for k in keep if k[0] in ("F.SilkS", "F.Paste", "F.Mask")]
    bottom = [k for k in keep if k[0] in ("B.Mask", "B.Paste", "B.SilkS")]
    mid = [(name, typ, None, t, mat, er, 0.02 if mat else None) for name, typ, t, mat, er in STACKUP]
    st.layers.clear()
    for name, typ, color, t, mat, er, tan in top + mid + bottom:
        st.layers.append(kicad.pcb.StackupLayer(
            name=name, type=typ, color=color,
            thickness=None if t is None else kicad.pcb.Thickness(thickness=t, locked=None),
            material=mat, epsilon_r=er, loss_tangent=tan,
        ))


def _zone(net_number, net_name, name, rect, keepout=False, layers=("F.Cu", "B.Cu")):
    x0, y0, x1, y1 = rect
    pts = [(x0, y0), (x1, y0), (x1, y1), (x0, y1)]
    na = kicad.pcb.E_zone_keepout.NOT_ALLOWED
    ok = kicad.pcb.E_zone_keepout.ALLOWED
    return kicad.pcb.Zone(
        net=net_number,
        net_name=net_name,
        layers=list(layers),
        layer=None,
        uuid=kicad.gen_uuid(""),
        name=name,
        polygon=kicad.pcb.Polygon(
            pts=kicad.pcb.Pts(xys=[kicad.pcb.Xy(x=x, y=y) for x, y in pts]),
            layers=[],
            layer=None,
            solder_mask_margin=None,
            stroke=None,
            fill=None,
            locked=None,
            uuid=None,  # KiCad rejects a uuid on a zone outline polygon
        ),
        min_thickness=0.2,
        filled_areas_thickness=False,
        fill=kicad.pcb.ZoneFill(
            enable=kicad.pcb.E_zone_fill_enable.YES,
            mode=None,
            hatch_thickness=0.0,
            hatch_gap=0.5,
            hatch_orientation=0,
            hatch_smoothing_level=0,
            hatch_smoothing_value=0,
            hatch_border_algorithm=kicad.pcb.E_zone_hatch_border_algorithm.HATCH_THICKNESS,
            hatch_min_hole_area=0.3,
            thermal_gap=0.3,
            thermal_bridge_width=0.3,
            smoothing=None,
            radius=1,
            island_area_min=10.0,
            arc_segments=None,
            island_removal_mode=None,
        ),
        hatch=kicad.pcb.Hatch(mode=kicad.pcb.E_zone_hatch_mode.EDGE, pitch=0.5),
        priority=0,
        keepout=kicad.pcb.ZoneKeepout(
            tracks=na, vias=na, pads=ok, copperpour=na, footprints=ok
        )
        if keepout
        else None,
        connect_pads=kicad.pcb.ConnectPads(mode=None, clearance=0.3),
        filled_polygon=[],
        placement=None,
        attr=None,
    )


def add_zones(pcb) -> None:
    """Inner planes, split at the isolation barrier, and a no-copper keep-out
    strip along the barrier on all four copper layers:
        In1.Cu: GND (USB half) | GND_ISO (DVM half)
        In2.Cu: +3V3 (USB half) | +5V_ISO (DVM half)
    The outer layers are left for signals (no pours)."""
    kicad.filter(pcb, "zones", pcb.zones, lambda z: z.name not in ZONE_NAMES)
    nets = {n.name: n.number for n in pcb.nets}
    e = 0.5  # pull-back from the board edge
    w, h = BOARD_W / 2 - e, BOARD_H / 2 - e
    pour_gap = BARRIER_HALF_GAP - 0.1  # just outside the keep-out strip
    usb, dvm = (-w, -h, w, -pour_gap), (-w, pour_gap, w, h)
    for z in (
        _zone(nets["GND"], "GND", "plane_GND", usb, layers=["In1.Cu"]),
        _zone(nets["GND_ISO"], "GND_ISO", "plane_GND_ISO", dvm, layers=["In1.Cu"]),
        _zone(nets["+3V3"], "+3V3", "plane_3V3", usb, layers=["In2.Cu"]),
        _zone(nets["+5V_ISO"], "+5V_ISO", "plane_5V_ISO", dvm, layers=["In2.Cu"]),
        _zone(
            0, "", "isolation_barrier",
            (-BOARD_W / 2, -BARRIER_HALF_GAP + 0.4, BOARD_W / 2, BARRIER_HALF_GAP - 0.4),
            keepout=True, layers=COPPER,
        ),
    ):
        kicad.insert(pcb, "zones", pcb.zones, z)


def place_rigid_group(pcb, by_addr, name, lib_layout, anchor, tx, ty) -> set[str]:
    """Restore a pre-routed library block's relative layout and move it, with
    its tracks and vias, so that its anchor footprint lands on (tx, ty).
    Returns the atopile addresses it placed."""
    lib = kicad.loads(kicad.pcb.PcbFile, lib_layout).kicad_pcb
    lib_fps = {props(fp)["atopile_address"]: fp for fp in lib.footprints}
    group = next(g for g in pcb.groups if g.name == name)
    members = set(group.members)
    tracks = [o for o in [*pcb.segments, *pcb.arcs, *pcb.vias] if o.uuid in members]

    # where the copied routing currently sits relative to the library layout
    def pts(objs):
        for o in objs:
            for k in ("start", "end", "at"):
                if getattr(o, k, None) is not None:
                    yield getattr(o, k)

    lib_tracks = [*lib.segments, *lib.arcs, *lib.vias]
    cur, ref = list(pts(tracks)), list(pts(lib_tracks))
    if len(cur) != len(ref):
        raise RuntimeError(f"group {name}: routing differs from {lib_layout}")
    ox = sum(p.x for p in cur) / len(cur) - sum(p.x for p in ref) / len(ref)
    oy = sum(p.y for p in cur) / len(cur) - sum(p.y for p in ref) / len(ref)
    a = lib_fps[anchor].at
    dx, dy = tx - (a.x + ox), ty - (a.y + oy)

    for o in tracks:
        PCB_Transformer.move_object(o, kicad.pcb.Xy(x=dx, y=dy))
    placed = set()
    for sub_addr, lfp in lib_fps.items():
        addr = f"{name}.{sub_addr}"
        x = lfp.at.x + ox + dx
        y = lfp.at.y + oy + dy
        PCB_Transformer.move_fp(by_addr[addr], kicad.pcb.Xyr(x=x, y=y, r=lfp.at.r or 0), lfp.layer)
        placed.add(addr)
    return placed


def main() -> int:
    pcb_file = kicad.loads(kicad.pcb.PcbFile, LAYOUT)
    pcb = pcb_file.kicad_pcb
    by_addr = {props(fp).get("atopile_address", ""): fp for fp in pcb.footprints}

    # Shift registers: fixed slots. (The slot order used to be derived from
    # the SKB pins on each register, but the pin map is now chosen for these
    # slots by scripts/pin_swap.py, so the slots must not follow it.)
    for ic, slot_x in zip(IC_SLOT_ORDER, IC_SLOTS_X):
        P[ic] = (slot_x, IC_ROW_Y, IC_ROTATION[ic.split("[")[0]], "F.Cu")
        P[ic.replace(".package", ".decoupling")] = (slot_x, IC_ROW_Y - 6.4, 0.0, "F.Cu")

    rigid = set()
    for name, (lib_layout, anchor, tx, ty) in RIGID_GROUPS.items():
        rigid |= place_rigid_group(pcb, by_addr, name, lib_layout, anchor, tx, ty)

    missing = [a for a in P if a not in by_addr]
    unplaced = [a for a in by_addr if a and a not in P and a not in rigid]
    if missing or unplaced:
        print("missing footprints:", missing, "\nunplaced footprints:", unplaced)
        return 1

    for addr, (x, y, r, layer) in P.items():
        PCB_Transformer.move_fp(by_addr[addr], kicad.pcb.Xyr(x=x, y=y, r=r), layer)

    set_layer_stack(pcb)
    add_zones(pcb)

    kicad.dumps(pcb_file, LAYOUT)
    print(f"placed {len(P) + len(rigid)} footprints -> {LAYOUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
