M48
; DRILL file KiCad 10.0.6-10.0.6~ubuntu24.04.1 date 2026-10-06T18:40:51
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-06T18:40:51+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-10.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
%
G90
G05
T1
X148.46Y-76.0
X153.54Y-74.984
X153.54Y-77.016
M30
